# Generated by Django 4.1.4 on 2022-12-24 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, verbose_name='Judul')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('stok', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama')),
                ('kelas', models.CharField(max_length=20, verbose_name='Kelas')),
                ('tempat_lahir', models.CharField(max_length=50, verbose_name='Tempat lahir')),
                ('tanggal_lahir', models.DateField(verbose_name='Tanggal lahir')),
            ],
        ),
        migrations.CreateModel(
            name='Peminjam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('batas_pengembalian', models.DateField(verbose_name='Batas Pengembalian')),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.buku', verbose_name='Buku yang dipinjam')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bukupinjam', to='master.siswa')),
            ],
        ),
    ]
