# Generated by Django 4.1.4 on 2022-12-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjam',
            name='dibuat',
            field=models.DateField(auto_now_add=True, verbose_name='Dibuat'),
        ),
    ]
