# Generated by Django 4.1.4 on 2022-12-24 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_peminjam_dibuat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjam',
            name='buku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinjambuku', to='master.buku', verbose_name='Buku yang dipinjam'),
        ),
    ]
